### ISSUE TITLE
Error with "width"

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/columns-of-cards#1]
Hello! 

I just finished my code and it all seems to work fine, but MarkBot says that my image's width is wrong even though it fits perfectly and I used the same one you provided in the guide 

@thomasjbradley

**Comment by thomasjbradley** [comment]
This is a little tricky. The `img` tag should have the standard `width: 100%` because it targets **all** images on the whole website.

But the images in our cards should be`100px` because they differ from _the whole website_.
